# Generated by Django 6.0.1 on 2026-02-03 04:28

import cloudinary.models
import cloudinary_storage.storage
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSeccionesCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_datos_personales', models.BooleanField(default=True)),
                ('mostrar_experiencia', models.BooleanField(default=True)),
                ('mostrar_reconocimientos', models.BooleanField(default=True)),
                ('mostrar_cursos', models.BooleanField(default=True)),
                ('mostrar_productos_academicos', models.BooleanField(default=True)),
                ('mostrar_productos_laborales', models.BooleanField(default=True)),
                ('mostrar_venta_garage', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración CV',
                'verbose_name_plural': 'Configuración CV',
            },
        ),
        migrations.CreateModel(
            name='DatosPersonales',
            fields=[
                ('idperfil', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionperfil', models.CharField(max_length=50)),
                ('perfilactivo', models.IntegerField()),
                ('apellidos', models.CharField(max_length=60)),
                ('nombres', models.CharField(max_length=60)),
                ('nacionalidad', models.CharField(max_length=20)),
                ('lugarnacimiento', models.CharField(max_length=60)),
                ('fechanacimiento', models.DateField()),
                ('numerocedula', models.CharField(max_length=10, unique=True)),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('estadocivil', models.CharField(max_length=50)),
                ('licenciaconducir', models.CharField(max_length=6)),
                ('telefonoconvencional', models.CharField(max_length=15)),
                ('telefonofijo', models.CharField(max_length=15)),
                ('direcciontrabajo', models.CharField(max_length=200)),
                ('direcciondomiciliaria', models.CharField(max_length=200)),
                ('sitioweb', models.CharField(max_length=60)),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CursoRealizado',
            fields=[
                ('idcursorealizado', models.AutoField(primary_key=True, serialize=False)),
                ('nombrecurso', models.CharField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('totalhoras', models.CharField(max_length=100)),
                ('descripcioncurso', models.CharField(max_length=255)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('emailempresapatrocinadora', models.CharField(max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificados_cursos/')),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='task.datospersonales')),
            ],
            options={
                'db_table': 'CURSOSREALIZADOS',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('idexperiencialaboral', models.AutoField(primary_key=True, serialize=False)),
                ('cargodesempenado', models.CharField(max_length=200)),
                ('nombrempresa', models.CharField(max_length=50)),
                ('lugarempresa', models.CharField(max_length=200)),
                ('emailempresa', models.CharField(max_length=150)),
                ('sitiowebempresa', models.CharField(max_length=200)),
                ('nombrecontactoempresarial', models.CharField(max_length=100)),
                ('telefonocontactoempresarial', models.CharField(max_length=60)),
                ('fechainiciogestion', models.DateField()),
                ('fechafingestion', models.DateField(blank=True, null=True)),
                ('descripcionfunciones', models.CharField(max_length=255)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificadolaboral')),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='task.datospersonales')),
            ],
            options={
                'db_table': 'EXPERIENCIALABORAL',
            },
        ),
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('idproductoacademico', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerecurso', models.CharField(max_length=100)),
                ('clasificador', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='task.datospersonales')),
            ],
            options={
                'db_table': 'PRODUCTOSACADEMICOS',
            },
        ),
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('idproductoslaborales', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaproducto', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='task.datospersonales')),
            ],
            options={
                'db_table': 'PRODUCTOSLABORALES',
            },
        ),
        migrations.CreateModel(
            name='Reconocimiento',
            fields=[
                ('idreconocimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tiporeconocimiento', models.CharField(choices=[('Académico', 'Académico'), ('Público', 'Público'), ('Privado', 'Privado')], max_length=100)),
                ('fechareconocimiento', models.DateField()),
                ('descripcionreconocimiento', models.CharField(max_length=255)),
                ('entidadpatrocinadora', models.CharField(max_length=100)),
                ('nombrecontactoauspicia', models.CharField(max_length=100)),
                ('telefonocontactoauspicia', models.CharField(max_length=60)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('rutacertificado', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certificadoreconocimiento')),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='task.datospersonales')),
            ],
            options={
                'db_table': 'RECONOCIMIENTOS',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('important', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaGarage',
            fields=[
                ('idventagarage', models.AutoField(primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(max_length=100)),
                ('estadoproducto', models.CharField(choices=[('Excelente', 'Excelente'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=40)),
                ('descripcion', models.CharField(max_length=200)),
                ('valordelbien', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fechapublicacion', models.DateField(default=django.utils.timezone.now)),
                ('activarparaqueseveaenfront', models.BooleanField(default=True)),
                ('articulo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='articulo')),
                ('perfil', models.ForeignKey(db_column='idperfilconqueestaactivo', on_delete=django.db.models.deletion.CASCADE, to='task.datospersonales')),
            ],
            options={
                'db_table': 'VENTAGARAGE',
            },
        ),
    ]
