# Generated by Django 6.0.1 on 2026-02-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_curso_datospersonales_garage_logro_productoacademico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='fecha_logro',
            new_name='fecha_finalizacion',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='nombre_curso',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='producto',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='garage',
            old_name='fecha_publicacion',
            new_name='publicado_el',
        ),
        migrations.RenameField(
            model_name='productoacademico',
            old_name='proyecto',
            new_name='nombre_proyecto',
        ),
        migrations.RenameField(
            model_name='productolaboral',
            old_name='logros_clave',
            new_name='logro_clave',
        ),
        migrations.RenameField(
            model_name='productolaboral',
            old_name='herramienta',
            new_name='nombre_herramienta',
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logro',
            name='entidad',
            field=models.CharField(default='Institución', max_length=200),
        ),
    ]
